version: '1.3.2'
services:
  webos:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8088"
    volumes:
      - "${DATA_PATH}:/webos/web"
      - "${MOUNT_PATH}:/webos"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    image: a79520/webos:x86_64
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true

